# ==========================================================================
# CRE PROJECT SETTINGS FILE
# ==========================================================================
# Project-specific settings for CRE CLI targets.
# Each target defines cre-cli, account, and rpcs groups.
#
# Example custom target:
# my-target:
#   account:
#     workflow-owner-address: "0x123..."            # Optional: Owner wallet/MSIG address (used for --unsigned transactions)
#   rpcs:
#     - chain-name: ethereum-testnet-sepolia        # Required if your workflow interacts with this chain
#       url: "<select your own rpc url>"
#     - chain-name: ethereum-mainnet                # Required if your workflow interacts with this chain
#       url: "<select your own rpc url>"

# ==========================================================================
staging-settings:
  rpcs:
    - chain-name: celo-mainnet
      url: https://rpc.ankr.com/celo
    - chain-name: ethereum-testnet-sepolia
      url: https://ethereum-sepolia-rpc.publicnode.com

# ==========================================================================
production-settings:
  rpcs:
    - chain-name: celo-mainnet
      url: https://rpc.ankr.com/celo
    - chain-name: ethereum-testnet-sepolia
      url: https://ethereum-sepolia-rpc.publicnode.com
